/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MenuPrincipalController;
import Model.DAO.Banco;
import com.sun.glass.events.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Ramom Karllos
 */
public class AlterarProduto extends javax.swing.JFrame {
    
    private final MenuPrincipalController controller;
    
    /**
     * Creates new form AlterarProduto
     */
    public AlterarProduto() {
        initComponents();
        controller = new MenuPrincipalController(this);
        Banco.inicia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeOuCodigo = new javax.swing.JLabel();
        jTextFieldNomeOuCodigo = new javax.swing.JTextField();
        jLabelNovoValor = new javax.swing.JLabel();
        jTextFieldNovoValor = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        jLabelPlanoDeFundo1 = new javax.swing.JLabel();
        jLabelPlanoDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(681, 453));
        setMinimumSize(new java.awt.Dimension(681, 453));
        setPreferredSize(new java.awt.Dimension(681, 453));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNomeOuCodigo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabelNomeOuCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeOuCodigo.setText("Nome ou Codigo");
        getContentPane().add(jLabelNomeOuCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 150, 20));

        jTextFieldNomeOuCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeOuCodigoActionPerformed(evt);
            }
        });
        jTextFieldNomeOuCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomeOuCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeOuCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, 30));

        jLabelNovoValor.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabelNovoValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNovoValor.setText("Novo Valor");
        jLabelNovoValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabelNovoValorKeyPressed(evt);
            }
        });
        getContentPane().add(jLabelNovoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 150, 30));

        jTextFieldNovoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNovoValorActionPerformed(evt);
            }
        });
        jTextFieldNovoValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNovoValorKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldNovoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 120, 30));

        jButtonCancelar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jButtonCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCancelarKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 80, 30));

        jButtonAlterar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        jButtonAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAlterarKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 80, 30));

        jLabelNome.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 280, 50));

        jLabelPreco.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabelPreco.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(jLabelPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 280, 50));

        jLabelPlanoDeFundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/painel-login_3.png"))); // NOI18N
        getContentPane().add(jLabelPlanoDeFundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 340, 510));

        jLabelPlanoDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/educacao-financeira-supermercado-como-economizar-compras.jpg"))); // NOI18N
        getContentPane().add(jLabelPlanoDeFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(697, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeOuCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeOuCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeOuCodigoActionPerformed

    private void jTextFieldNomeOuCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeOuCodigoKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jTextFieldNomeOuCodigoKeyPressed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        this.controller.AlterarProduto();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAlterarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.controller.AlterarProduto();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jButtonAlterarKeyPressed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCancelarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCancelarKeyPressed

    private void jTextFieldNovoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNovoValorActionPerformed
        
    }//GEN-LAST:event_jTextFieldNovoValorActionPerformed

    private void jTextFieldNovoValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNovoValorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.controller.AlterarProduto();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jTextFieldNovoValorKeyPressed

    private void jLabelNovoValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelNovoValorKeyPressed
        
    }//GEN-LAST:event_jLabelNovoValorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeOuCodigo;
    private javax.swing.JLabel jLabelNovoValor;
    private javax.swing.JLabel jLabelPlanoDeFundo;
    private javax.swing.JLabel jLabelPlanoDeFundo1;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JTextField jTextFieldNomeOuCodigo;
    private javax.swing.JTextField jTextFieldNovoValor;
    // End of variables declaration//GEN-END:variables

    public JTextField getTextNomeOuCodigo() {
        return jTextFieldNomeOuCodigo;
    }
    
    public void setTextNomeOuCodigo(JTextField TextNomeOuCodigo) {
        this.jTextFieldNomeOuCodigo = TextNomeOuCodigo;
    }

    public JLabel getjLabelPreco() {
        return jLabelPreco;
    }

    public void setjLabelPreco(JLabel jLabelPreco) {
        this.jLabelPreco = jLabelPreco;
    }

    public JLabel getjLabelNome() {
        return jLabelNome;
    }

    public void setjLabelNome(JLabel jLabelNome) {
        this.jLabelNome = jLabelNome;
    }
    
    public JTextField getTextNovoValor() {
        return jTextFieldNovoValor;
    }
    
    public void setTextNovoValor(JTextField TextNovoValor) {
        this.jTextFieldNovoValor = TextNovoValor;
    }
    
    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }
    
}
