/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MenuPrincipalController;
import Model.DAO.Banco;
import com.sun.glass.events.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Ramom Karllos
 */
public class ExcluirProduto extends javax.swing.JFrame {

    private final MenuPrincipalController controller;

    /**
     * Creates new form ExcluirProduto
     */
    public ExcluirProduto() {
        initComponents();
        controller = new MenuPrincipalController(this);
        Banco.inicia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCPF = new javax.swing.JLabel();
        jTextFieldNomeOuCodigo = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        jLabelPlanoDeFundo1 = new javax.swing.JLabel();
        jLabelPlanoDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(680, 449));
        setMinimumSize(new java.awt.Dimension(680, 449));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCPF.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPF.setText("Nome ou Codigo");
        getContentPane().add(jLabelCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 150, 20));

        jTextFieldNomeOuCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeOuCodigoActionPerformed(evt);
            }
        });
        jTextFieldNomeOuCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomeOuCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeOuCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, 30));

        jButtonExcluir.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jButtonExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonExcluirKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 80, 30));

        jButtonCancelar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jButtonCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCancelarKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 80, 30));

        jLabelNome.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 280, 60));

        jLabelPreco.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabelPreco.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(jLabelPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 280, 50));

        jLabelPlanoDeFundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/painel-login_3.png"))); // NOI18N
        getContentPane().add(jLabelPlanoDeFundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 340, 510));

        jLabelPlanoDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/educacao-financeira-supermercado-como-economizar-compras.jpg"))); // NOI18N
        getContentPane().add(jLabelPlanoDeFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(696, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        this.controller.ExcluirProduto();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonExcluirKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.controller.ExcluirProduto();
        }
    }//GEN-LAST:event_jButtonExcluirKeyPressed

    private void jTextFieldNomeOuCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeOuCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeOuCodigoActionPerformed

    private void jTextFieldNomeOuCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeOuCodigoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.controller.ExcluirProduto();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jTextFieldNomeOuCodigoKeyPressed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCancelarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCancelarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPlanoDeFundo;
    private javax.swing.JLabel jLabelPlanoDeFundo1;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JTextField jTextFieldNomeOuCodigo;
    // End of variables declaration//GEN-END:variables
    public JTextField getTextNomeOuCodigo() {
        return jTextFieldNomeOuCodigo;
    }
    
    public void setTextNomeOuCodigo(JTextField TextNomeOuCodigo) {
        this.jTextFieldNomeOuCodigo = TextNomeOuCodigo;
    }

    public JLabel getjLabelPreco() {
        return jLabelPreco;
    }

    public void setjLabelPreco(JLabel jLabelPreco) {
        this.jLabelPreco = jLabelPreco;
    }

    public JLabel getjLabelNome() {
        return jLabelNome;
    }

    public void setjLabelNome(JLabel jLabelNome) {
        this.jLabelNome = jLabelNome;
    }
    
    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

}
