/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoginController;
import Model.DAO.Banco;
import com.sun.glass.events.KeyEvent;

/**
 *
 * @author Ramom Karllos
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private final LoginController controller;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        Login login = new Login();
        controller = new LoginController(login);
        Banco.inicia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFuncionalidade = new javax.swing.JLabel();
        jLabelFuncionalidade1 = new javax.swing.JLabel();
        jLabelFuncionalidade2 = new javax.swing.JLabel();
        jLabelFuncionalidade3 = new javax.swing.JLabel();
        jLabelFuncionalidade4 = new javax.swing.JLabel();
        jLabelFuncionalidade5 = new javax.swing.JLabel();
        jLabelFuncionalidade6 = new javax.swing.JLabel();
        jLabelFuncionalidade7 = new javax.swing.JLabel();
        jLabelfundo = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuItemFuncionario = new javax.swing.JMenuItem();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jMenuOperacao = new javax.swing.JMenu();
        jMenuItemConsultarPreco = new javax.swing.JMenuItem();
        jMenuItemRealizarVenda = new javax.swing.JMenuItem();
        jMenuItemExcluirProduto = new javax.swing.JMenuItem();
        jMenuItemAlterarPreco = new javax.swing.JMenuItem();
        jMenuItemRelatorioDeEstoque = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DevelopersMarket");
        setExtendedState(6);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFuncionalidade.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabelFuncionalidade.setForeground(new java.awt.Color(0, 153, 0));
        jLabelFuncionalidade.setText("FUNCIONALIDADES");
        getContentPane().add(jLabelFuncionalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, 370, 60));

        jLabelFuncionalidade1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabelFuncionalidade1.setForeground(new java.awt.Color(0, 153, 0));
        jLabelFuncionalidade1.setText("Cadastrar Usuario = F1");
        getContentPane().add(jLabelFuncionalidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 440, 60));

        jLabelFuncionalidade2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabelFuncionalidade2.setForeground(new java.awt.Color(0, 153, 0));
        jLabelFuncionalidade2.setText("Excluir Produto = F5");
        getContentPane().add(jLabelFuncionalidade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, 450, 60));

        jLabelFuncionalidade3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabelFuncionalidade3.setForeground(new java.awt.Color(0, 153, 0));
        jLabelFuncionalidade3.setText("Realizar Venda = F4");
        getContentPane().add(jLabelFuncionalidade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 400, 60));

        jLabelFuncionalidade4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabelFuncionalidade4.setForeground(new java.awt.Color(0, 153, 0));
        jLabelFuncionalidade4.setText("Cadastrar Produto = F2");
        getContentPane().add(jLabelFuncionalidade4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 440, 60));

        jLabelFuncionalidade5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabelFuncionalidade5.setForeground(new java.awt.Color(0, 153, 0));
        jLabelFuncionalidade5.setText("Alterar Preço = F6");
        getContentPane().add(jLabelFuncionalidade5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 680, 450, 60));

        jLabelFuncionalidade6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabelFuncionalidade6.setForeground(new java.awt.Color(0, 153, 0));
        jLabelFuncionalidade6.setText("Relatorio de Estoque = F7");
        getContentPane().add(jLabelFuncionalidade6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 740, 500, 60));

        jLabelFuncionalidade7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabelFuncionalidade7.setForeground(new java.awt.Color(0, 153, 0));
        jLabelFuncionalidade7.setText("Consultar Preço = F3");
        getContentPane().add(jLabelFuncionalidade7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, 450, 60));

        jLabelfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/05596b462815ea8.jpg"))); // NOI18N
        getContentPane().add(jLabelfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/naom_5982f96d4ab62.jpg"))); // NOI18N
        jLabelFundoPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabelFundoPrincipalKeyPressed(evt);
            }
        });
        getContentPane().add(jLabelFundoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        jMenuCadastrar.setText("Cadastrar");

        jMenuItemFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/cliente-icon.png"))); // NOI18N
        jMenuItemFuncionario.setText("Funcionario");
        jMenuItemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionarioActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemFuncionario);

        jMenuItemProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/shopping-bag_1.png"))); // NOI18N
        jMenuItemProduto.setText("Produto");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemProduto);

        jMenuBar1.add(jMenuCadastrar);

        jMenuOperacao.setText("Operação");

        jMenuItemConsultarPreco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemConsultarPreco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/Consultar Preço.png"))); // NOI18N
        jMenuItemConsultarPreco.setText("Consultar Preço");
        jMenuItemConsultarPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarPrecoActionPerformed(evt);
            }
        });
        jMenuOperacao.add(jMenuItemConsultarPreco);

        jMenuItemRealizarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemRealizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/Realizar Venda.png"))); // NOI18N
        jMenuItemRealizarVenda.setText("Realizar Venda");
        jMenuItemRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRealizarVendaActionPerformed(evt);
            }
        });
        jMenuOperacao.add(jMenuItemRealizarVenda);

        jMenuItemExcluirProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItemExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/Excluir Produto.png"))); // NOI18N
        jMenuItemExcluirProduto.setText("Excluir Produto");
        jMenuItemExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirProdutoActionPerformed(evt);
            }
        });
        jMenuOperacao.add(jMenuItemExcluirProduto);

        jMenuItemAlterarPreco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItemAlterarPreco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/Alterar Preço.png"))); // NOI18N
        jMenuItemAlterarPreco.setText("Alterar Preço");
        jMenuItemAlterarPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarPrecoActionPerformed(evt);
            }
        });
        jMenuOperacao.add(jMenuItemAlterarPreco);

        jMenuItemRelatorioDeEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItemRelatorioDeEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Icons/Relatorio de Estoque.png"))); // NOI18N
        jMenuItemRelatorioDeEstoque.setText("Relatorio de Estoque");
        jMenuOperacao.add(jMenuItemRelatorioDeEstoque);

        jMenuBar1.add(jMenuOperacao);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionarioActionPerformed
        
        Login login = new Login(2);
        login.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_jMenuItemFuncionarioActionPerformed

    private void jMenuItemRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRealizarVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRealizarVendaActionPerformed

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
        Login login = new Login(3);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    private void jMenuItemConsultarPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarPrecoActionPerformed
        ConsultarPreco consultarPreco = new ConsultarPreco();
        consultarPreco.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarPrecoActionPerformed

    private void jMenuItemExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirProdutoActionPerformed
        Login login = new Login(4);
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluirProdutoActionPerformed

    private void jMenuItemAlterarPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarPrecoActionPerformed
        Login login = new Login(5);
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlterarPrecoActionPerformed

    private void jLabelFundoPrincipalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelFundoPrincipalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_jLabelFundoPrincipalKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFuncionalidade;
    private javax.swing.JLabel jLabelFuncionalidade1;
    private javax.swing.JLabel jLabelFuncionalidade2;
    private javax.swing.JLabel jLabelFuncionalidade3;
    private javax.swing.JLabel jLabelFuncionalidade4;
    private javax.swing.JLabel jLabelFuncionalidade5;
    private javax.swing.JLabel jLabelFuncionalidade6;
    private javax.swing.JLabel jLabelFuncionalidade7;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelfundo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenuItem jMenuItemAlterarPreco;
    private javax.swing.JMenuItem jMenuItemConsultarPreco;
    private javax.swing.JMenuItem jMenuItemExcluirProduto;
    private javax.swing.JMenuItem jMenuItemFuncionario;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemRealizarVenda;
    private javax.swing.JMenuItem jMenuItemRelatorioDeEstoque;
    private javax.swing.JMenu jMenuOperacao;
    // End of variables declaration//GEN-END:variables
}
